<?php
namespace MailPoetVendor;
if (!defined('ABSPATH')) exit;
// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return ComposerAutoloaderInit2318eb61f0c001fa720d76365ccacd32::getLoader();
